version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform
        entrypoint: ["/bin/sh"]
    steps:
      - checkout
      - run:
          name: install terragrunt
          command: |
            curl -L 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.1/terragrunt_linux_amd64' > /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
      - run: apk add make
      - run: make validate

  plan:
    docker:
      - image: hashicorp/terraform
        entrypoint: ["/bin/sh"]
    environment:
      TERRAGRUNT_ENV: test-ci
    steps:
      - checkout
      - run:
          name: install terragrunt
          command: |
            curl -L 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.1/terragrunt_linux_amd64' > /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
      - run: apk add make
      - run:
          name: terragrunt plan
          command: make plan
      - persist_to_workspace:
          root: .
          paths:
            - test-ci/vpc/.terragrunt-cache
            - test-ci/db/.terragrunt-cache
            - test-ci/app/.terragrunt-cache

  apply:
    docker:
      - image: hashicorp/terraform
        entrypoint: ["/bin/sh"]
    environment:
      TERRAGRUNT_ENV: test-ci
    steps:
      - checkout
      - run:
          name: install terragrunt
          command: |
            curl -L 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.1/terragrunt_linux_amd64' > /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
      - run: apk add make
      - attach_workspace:
          at: .
      - run:
          name: terragrunt apply
          command: make apply

workflows:
  version: 2
  commit:
    jobs:
      - validate

      - plan:
          requires:
            - validate

      - hold:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only:
                - cd

      - apply:
          requires:
            - hold
