version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform
        entrypoint: ["/bin/sh"]
    steps:
      - checkout
      - run:
          name: install terragrunt
          command: |
            curl -L 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.1/terragrunt_linux_amd64' > /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
      - run:
          name: validate test
          command: |
            cd test-ci
            terragrunt validate-all

  plan:
    docker:
      - image: hashicorp/terraform
        entrypoint: ["/bin/sh"]
    environment:
      terragrunt_env: test-ci
    steps:
      - checkout
      - run:
          name: install terragrunt
          command: |
            curl -L 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.1/terragrunt_linux_amd64' > /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
      - run:
          name: terragrunt plan
          command: |
            cd $terragrunt_env

            cd ./vpc
            terragrunt plan -out=vpc.tfplan

            cd ../db
            terragrunt plan -out=db.tfplan

            cd ../app
            terragrunt plan -out=app.tfplan
      - persist_to_workspace:
          root: .
          paths:
            - test-ci/vpc/.terragrunt-cache
            - test-ci/db/.terragrunt-cache
            - test-ci/app/.terragrunt-cache

  apply:
    docker:
      - image: hashicorp/terraform
        entrypoint: ["/bin/sh"]
    environment:
      terragrunt_env: test-ci
    steps:
      - checkout
      - run:
          name: install terragrunt
          command: |
            curl -L 'https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.1/terragrunt_linux_amd64' > /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
      - attach_workspace:
          at: .
      - run:
          name: terragrunt apply
          command: |
            cd $terragrunt_env

            cd ./vpc
            terragrunt apply vpc.tfplan

            cd ../db
            terragrunt apply db.tfplan

            cd ../app
            terragrunt apply app.tfplan

workflows:
  version: 2
  commit:
    jobs:
      - validate

      - plan:
          requires:
            - validate

      - hold:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only:
                - cd

      - apply:
          requires:
            - hold
